[tool.poetry]
name = "mire-baseline"
version = "0.1.0"
description = ""
authors = ["均闻 <liujunwen.ljw@taobao.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
