### model，base model的路径
model_name_or_path: Qwen2-VL-7B-Instruct

### method
stage: sft
do_train: true
finetuning_type: lora
lora_target: all

### dataset
dataset: mire_train  # 这里配置自己的数据集
template: qwen2_vl
cutoff_len: 2048
max_samples: 1000  # 这个参数匹配自己的数据集或设置大点
overwrite_cache: true
preprocessing_num_workers: 16
val_size: 0.1

### output
output_dir: /data/users/wanjunhui/Task/Research_core/LLM/LLaMA-Factory_wjh/saves/qwen2_vl-7b/lora/sft
logging_steps: 10
save_steps: 50
plot_loss: true
overwrite_output_dir: true

### train
per_device_train_batch_size: 1
gradient_accumulation_steps: 8
learning_rate: 1.0e-4
num_train_epochs: 3.0
lr_scheduler_type: cosine
warmup_ratio: 0.1
bf16: true
ddp_timeout: 180000000

### eval
val_size: 0.1
per_device_eval_batch_size: 1
eval_strategy: steps
eval_steps: 20